// Plat the map: every lot public/city/map.json affords, with a stable id and
// address, written to public/city/lots.json. The client draws vacant lots
// from it, the manifest builder allocates from it, and the submit API checks
// requested lot ids against it.
//
// `--check` (CI) fails instead of writing when the plat on disk is stale, so
// an edit to map.json cannot merge without its consequences. It also refuses
// to let a lot the registry has HANDED OUT disappear or move: a claimed
// address is forever, and a map edit that would break that is a bug in the
// edit, not something to write silently.
//
// Usage: node scripts/build-map.mjs [--check]
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { platLots, roadSegments } from '../public/js/city-map.mjs';

const root = new URL('..', import.meta.url).pathname;
const pub = join(root, 'public');
const check = process.argv.includes('--check');
const map = JSON.parse(readFileSync(join(pub, 'city', 'map.json'), 'utf8'));
const venues = existsSync(join(pub, 'venues', 'index.json'))
  ? JSON.parse(readFileSync(join(pub, 'venues', 'index.json'), 'utf8')).venues || []
  : [];

const plat = platLots(map, venues);
const segs = roadSegments(map);
let failed = 0;

// A claimed lot must survive every map edit, at the same place. The
// comparison is against the REGISTRY's frozen record of where each held lot
// was placed (`placed`, written by build-manifest at assignment), never
// against the plat on disk: a PR that edits the map and regenerates the plat
// carries a plat that agrees with itself, and that would have passed.
const registryPath = join(pub, 'plots', 'lots.json');
const registry = existsSync(registryPath) ? JSON.parse(readFileSync(registryPath, 'utf8')) : { lots: {} };
const placed = registry.placed || {};
for (const [slug, id] of Object.entries(registry.lots || {})) {
  const now = plat.lots[id];
  const was = placed[id];
  if (!now) { console.log(`FAIL  ${slug} holds ${id}, which this map no longer affords`); failed += 1; continue; }
  if (was && (was.x !== now.x || was.z !== now.z || was.yaw !== now.yaw)) {
    console.log(`FAIL  ${id} (${slug}) was placed at (${was.x}, ${was.z}) and this map puts it at (${now.x}, ${now.z}) — a claimed address never moves`);
    failed += 1;
  }
}

const out = JSON.stringify({
  version: map.version || '0.1',
  comment: 'GENERATED by scripts/build-map.mjs from city/map.json — never hand-edit. Every lot the city affords, claimed or not; plots/index.json says which are vacant.',
  spawn: { x: map.spawn.x, z: map.spawn.z, yaw: map.spawn.yaw },
  centre: map.centre || [0, 0],
  roads: plat.roads,
  lots: plat.lots,
}, null, 2) + '\n';

for (const r of Object.values(plat.roads)) {
  const road = map.roads.find((q) => q.id === r.id);
  const L = segs.filter((s) => s.road === road).reduce((m, s) => m + s.L, 0);
  console.log(`${r.name.padEnd(20)} ${String(L.toFixed(0)).padStart(4)} m  ${String(r.lots.length).padStart(3)} lots  ${r.lots[0]} .. ${r.lots.at(-1)}`);
}
const platPath = join(pub, 'city', 'lots.json');
if (check) {
  const current = existsSync(platPath) ? readFileSync(platPath, 'utf8') : '';
  if (current !== out) { console.log('FAIL  public/city/lots.json is stale — run `npm run map`'); failed += 1; }
  else console.log('public/city/lots.json is current');
} else if (!failed) {
  writeFileSync(platPath, out);
  console.log(`wrote public/city/lots.json (${Object.keys(plat.lots).length} lots on ${Object.keys(plat.roads).length} roads)`);
}
if (failed) process.exit(1);
