// POST /api/plots/submit — the no-fork submission path (ai-directory model).
// Accepts JSON { plot: {...}, glb_base64 | glb_url,
//                media?: { "name.ext": base64 }, media_urls?: { "name.ext": url } },
// runs the exact published checks, verifies the backlink (unless the domain
// is pre-trusted, e.g. existing PromptFrenzy AI-directory listees), then
// creates the PR with the directory bot's credentials. The submitter needs
// nothing but this one HTTP call.
//
// Env: GITHUB_TOKEN (bot PAT with repo scope), GITHUB_REPO ("owner/name").
// Without a token — or with { dry: true } — it validates and reports only.
import { validateIdentity, validateGlb, probeWalkability, validateMediaDecl, probeSurfaces, probeMediaFiles, SPEC } from '../lib/validate-plot.mjs';
import { fetchAsset } from '../lib/fetch-asset.mjs';
import { pickLot } from '../public/js/city-map.mjs';
import { DEFAULT_CATEGORY } from '../public/js/categories.mjs';
import { hostOf, apexHost, sameSite, ownerKey, classifyUrl } from '../lib/submitter-host.mjs';
import { buildTemplate, TEMPLATE_ID, TEMPLATE_VERSION, PICTURE_NODES } from '../lib/template-shop.mjs';
import { fetchSiteMeta, imageKind } from '../lib/site-meta.mjs';
import { readFileSync } from 'node:fs';

const TRUSTED = JSON.parse(readFileSync(new URL('../trusted.json', import.meta.url)));
// The plat: every lot the map affords, generated by scripts/build-map.mjs. It
// is read from the deployed bundle, so a lot id is checked against the map
// this deployment was built with; which lots are FREE comes from the registry
// on main, below, because the map changes rarely and the registry every claim.
const PLAT = JSON.parse(readFileSync(new URL('../public/city/lots.json', import.meta.url)));

// Per-file ceilings, read from the SPEC the docs publish rather than repeated
// here. The two had already drifted: the spec caps screens at 16 MiB TOTAL and
// this table was checking 16 MiB PER FILE, so two screens could pass at double
// the published budget. A number that lives in one place cannot drift again.
const SM = SPEC.media;
const AUDIO_MAX = SM.ambient_audio.max_bytes;
const PICTURE_MAX = SM.pictures.max_bytes_each;
const SCREENS_TOTAL = SM.screens.max_bytes_total;
// A logo is fetched, read for its shape and thrown away — it never lands in
// the bundle — so it shares the picture budget rather than earning its own.
const LOGO_MAX = PICTURE_MAX;
const FEED_JSON_MAX = 64 << 10;              // a bundled live-feed document
const MEDIA_MAX = {
  m4a: AUDIO_MAX, mp3: AUDIO_MAX, ogg: AUDIO_MAX,
  mp4: SCREENS_TOTAL,                        // one screen may spend the whole allowance
  png: PICTURE_MAX, jpg: PICTURE_MAX, jpeg: PICTURE_MAX, webp: PICTURE_MAX,
  json: FEED_JSON_MAX,
};

// The platform rejects a request body over this BEFORE the function runs: a
// bare text/plain 413, no JSON, no report, nothing this code can catch or
// explain. Base64 inflates every file by a third on the way in, so the real
// ceiling for an inline bundle is ~3.3 MB of actual bytes — well under the sum
// of the published per-file caps. Bundles that big must come in by URL.
const REQUEST_BODY_LIMIT = 4.5e6;
const MB = (n) => `${(n / 1e6).toFixed(2)} MB`;
const KiB = (n) => `${(n / 1024).toFixed(0)} KiB`;

// What the panel renderer can actually draw. Measured in the real 512x384
// canvas with the fonts renderFeed uses, at the x each string starts from:
// these are the lengths at which text runs off the panel, not a style guide.
const PANEL = { big: 8, title: 28, sub: 33, bars: 16 };

// The old check asked only whether one of the four keys existed, so a feed
// whose bars were strings passed the dry run and then drew an empty chart on
// the lot. Type errors fail here; things that merely won't fit are reported in
// the detail, because a clipped headline is the author's call, not a defect.
function feedShape(d) {
  if (!d || typeof d !== 'object' || Array.isArray(d)) {
    return { ok: false, why: 'is not a JSON object' };
  }
  if (!['title', 'big', 'sub', 'bars'].some((k) => k in d)) {
    return { ok: false, why: 'has none of title, big, sub, bars' };
  }
  for (const k of ['title', 'big', 'sub']) {
    const v = d[k];
    if (k in d && v !== null && typeof v !== 'string' && typeof v !== 'number') {
      return { ok: false, why: `${k} must be a string or number (got ${Array.isArray(v) ? 'array' : typeof v})` };
    }
  }
  const notes = [];
  if ('bars' in d) {
    if (!Array.isArray(d.bars)) {
      return { ok: false, why: `bars must be an array of plain numbers (got ${typeof d.bars})` };
    }
    const bad = d.bars.filter((b) => typeof b !== 'number' || !Number.isFinite(b)).length;
    if (bad) {
      return { ok: false, why: `${bad} of ${d.bars.length} bars are not finite numbers — those draw nothing` };
    }
    if (d.bars.length > PANEL.bars) notes.push(`${d.bars.length} bars, only the first ${PANEL.bars} are drawn`);
  }
  for (const [k, max] of [['big', PANEL.big], ['title', PANEL.title], ['sub', PANEL.sub]]) {
    const len = String(d[k] ?? '').length;
    if (len > max) notes.push(`${k} is ${len} chars, ~${max} fit on the panel`);
  }
  return { ok: true, notes };
}

const CITY_ORIGIN = 'https://otra.city';
const corsOpen = (v) => v === '*' || (v || '').toLowerCase() === CITY_ORIGIN;

// A visitor's browser applies CORS to EVERY hop, so a redirect that does not
// itself carry Access-Control-Allow-Origin stops the fetch dead however open
// the destination is. node's fetch follows redirects with no CORS at all, so
// walking them by hand is the only way this check can mean what it says —
// otherwise a plot passes the dry run and its panel never leaves the fallback
// texture in the real city. (Found exactly this on a live plot.)
async function fetchLikeABrowser(url, maxHops = 3) {
  let current = url;
  for (let hop = 0; ; hop++) {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 8000);
    const r = await fetch(current, {
      signal: ctl.signal,
      redirect: 'manual',
      headers: { 'user-agent': 'otra-city-bot/1.0', origin: CITY_ORIGIN },
    });
    clearTimeout(t);
    const cors = r.headers.get('access-control-allow-origin');
    const location = r.headers.get('location');
    if (r.status >= 300 && r.status < 400 && location) {
      const next = new URL(location, current).href;
      if (!corsOpen(cors)) {
        return { blocked: `${current} answers ${r.status} -> ${next} without "Access-Control-Allow-Origin" ` +
          `on the redirect itself. A browser stops there even though the destination is open, so the panel ` +
          `would never leave its authored texture. Declare ${next} as your feed url, or send the header on the redirect too.` };
      }
      if (hop >= maxHops) return { blocked: `more than ${maxHops} redirects from ${url}` };
      current = next;
      continue;
    }
    return { r, cors, finalUrl: current };
  }
}

// Live-feed dry check: fetch the declared endpoint (or parse the bundled
// file) and validate the shape, so a broken feed fails HERE, not on the lot.
async function checkFeed(feed, media) {
  try {
    if (feed.url) {
      const hop = await fetchLikeABrowser(feed.url);
      if (hop.blocked) return { ok: false, detail: hop.blocked };
      const { r, cors } = hop;
      if (!r.ok) return { ok: false, detail: `GET ${feed.url} -> ${r.status}` };
      const data = await r.json();
      const shape = feedShape(data);
      if (!shape.ok) return { ok: false, detail: `response ${shape.why} — the panel needs {title, big, sub, bars[]}` };
      const fits = shape.notes.length ? ` — note: ${shape.notes.join('; ')}` : '';
      return {
        ok: corsOpen(cors),
        detail: (corsOpen(cors)
          ? `endpoint OK, shape OK, CORS OK (panel falls back to its authored texture if it ever breaks)`
          : `shape OK but missing "Access-Control-Allow-Origin: *" — the browser polls this URL directly, so without CORS the panel will only ever show its authored texture`) + fits,
      };
    }
    const name = (feed.file || '').split('/').pop();
    const b64 = media[name];
    if (!b64) return { ok: false, detail: `bundled feed ${feed.file} not found in media` };
    const data = JSON.parse(Buffer.from(b64, 'base64').toString('utf8'));
    const shape = feedShape(data);
    if (!shape.ok) return { ok: false, detail: `bundled feed ${shape.why} — the panel needs {title, big, sub, bars[]}` };
    return { ok: true,
      detail: `bundled feed OK — update it by resubmitting; upgrade to a live url any time` +
        (shape.notes.length ? ` — note: ${shape.notes.join('; ')}` : '') };
  } catch (e) {
    return { ok: false, detail: `feed check failed: ${e.name || e}` };
  }
}

// Returns the parsed bundle AND the wire size, so the report can tell a
// submitter how close they came to the body limit above — the difference
// between "you have room for a longer video" and a mystery 413 next time.
async function readBody(req) {
  if (req.body) {
    const raw = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
    return { body: typeof req.body === 'string' ? JSON.parse(req.body) : req.body,
      bytes: Buffer.byteLength(raw) };
  }
  const chunks = [];
  for await (const c of req) chunks.push(c);
  const buf = Buffer.concat(chunks);
  return { body: JSON.parse(buf.toString('utf8')), bytes: buf.length };
}

// Proof that the submitter controls the domain they are claiming: plain HTTP,
// no JavaScript executed, scanning the page they declared for their own
// permalink. Refusing to run JS is the anti-spoof property, not a limitation.
//
// The load-bearing line is the same-site guard on the FINAL url. Without it,
// declaring a domain with an open redirect — or a shortener, or any host that
// forwards elsewhere — lets you satisfy the check with a page you control on
// somebody else's domain, and the city then carries their name on your board
// and hands you their identity for every future update. Redirects WITHIN the
// site are fine; leaving it is the whole attack.
async function checkBacklink(url, slug) {
  const domain = hostOf(url);
  // The city's own pages cannot vouch for a plot: the city republishes every
  // live permalink itself (GET /api/plots/<slug> answers with one), so a
  // needle found on this domain proves nothing about authorization. The one
  // exception is the exhibition page, whose cards only an organiser edits —
  // a card there IS the grant, and removing one freezes its slug
  // (docs/frontier-house/ORGANISER.md).
  if (apexHost(url) === 'otra.city' && new URL(url).pathname !== '/houses') {
    return { ok: false, mode: 'city-host', detail:
      `${url} is on the city's own domain, which cannot vouch for a plot — the only ` +
      `page here that counts is https://otra.city/houses, and only for the slugs listed on it` };
  }
  if (TRUSTED.domains.includes(domain)) {
    return { ok: true, mode: 'trusted', detail: `${domain} is pre-trusted (existing directory listing)` };
  }
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 8000);
    const r = await fetch(url, { signal: ctl.signal, redirect: 'follow', headers: { 'user-agent': 'otra-city-bot/1.0' } });
    clearTimeout(t);
    if (!r.ok) return { ok: false, mode: 'fetched', detail: `GET ${url} -> ${r.status}` };
    if (r.url && !sameSite(url, r.url)) {
      return { ok: false, mode: 'redirected', detail:
        `${url} redirects to ${r.url}, which is ${apexHost(r.url)} and not ${apexHost(url)}. ` +
        `The permalink has to be on the domain you are claiming — that redirect is what proving ownership ` +
        `would otherwise let anyone skip. Declare the url visitors actually land on.` };
    }
    const html = (await r.text()).slice(0, 512 * 1024);
    const needle = `otra.city/s/${slug}`;
    const found = html.includes(needle);
    return {
      ok: found,
      mode: 'fetched',
      detail: found ? `backlink to ${needle} found` : `page does not contain ${needle} — add your plot permalink first`,
    };
  } catch (e) {
    return { ok: false, mode: 'fetched', detail: `could not fetch ${url}: ${e.name}` };
  }
}

// --- A listing --------------------------------------------------------------
// A submission with no build of its own is a directory listing: a url, a name,
// a sentence, a category — the payload an agent already writes for an AI
// directory. The city builds the shopfront (lib/template-shop.mjs) and puts
// the site's own pictures on it: `images` if the listing sent any, else the
// page's og:image, else lit blank plates. Everything the template produces
// then meets the same validator a hand-built bundle meets, in this same
// request, so a clean dry run means exactly what it means for a custom build.
const IMAGE_MAX = 6;

// The board's one-liner, from the listing's description when it sent no
// tagline: cut inside 80 chars, never mid-word.
//
// Prefer a clause boundary over a word boundary. Cutting at a word leaves a
// sentence severed mid-thought — PasteGuard's first tagline read "…tokens, and
// PII before pasting…" and stopped one word before "into AI chats", which is
// the half that says what it is FOR. Cutting at the last comma instead gives a
// phrase that ends where a phrase should, and needs no ellipsis because
// nothing was left dangling.
export function deriveTagline(description) {
  const s = String(description || '').replace(/\s+/g, ' ').trim();
  if (s.length <= 80) return s;
  const head = s.slice(0, 80);
  const clause = Math.max(
    head.lastIndexOf('. '), head.lastIndexOf(', '),
    head.lastIndexOf('; '), head.lastIndexOf(' — '), head.lastIndexOf(' – '),
  );
  if (clause >= 40) return s.slice(0, clause).replace(/[\s,;:–—-]+$/, '');
  const cut = s.slice(0, 79);
  const sp = cut.lastIndexOf(' ');
  return (sp > 40 ? cut.slice(0, sp) : cut).replace(/[\s,;:–—-]+$/, '') + '…';
}

// Runs BEFORE identity validation so the derived fields are what gets checked.
// The tagline is derived for every submission that sent a description and no
// tagline — a hand-built bundle with directory fields is welcome too; the
// shop type and the default category are a listing's alone.
function prepareListing(plot, listing) {
  if (!plot.tagline && typeof plot.description === 'string') plot.tagline = deriveTagline(plot.description);
  if (!listing) return;
  if (!plot.type) plot.type = 'shop';
  if (!plot.category) plot.category = DEFAULT_CATEGORY;
}

const HEX = /^#?[0-9a-f]{6}$/i;
const norm = (c) => (HEX.test(String(c || '')) ? `#${String(c).replace('#', '').toLowerCase()}` : null);

/** The two colours the shopfront is built from. `colors` is the richer form;
 *  `color` remains the accent on its own, which is what every earlier listing
 *  sent and what the kerb board and the map still read. */
export function resolveColors(plot) {
  const c = plot.colors && typeof plot.colors === 'object' ? plot.colors : {};
  return {
    accent: norm(c.accent) || norm(plot.color) || null,
    primary: norm(c.primary) || null,
  };
}

// `fetchImage` is injectable so the check suite can hand it pictures without
// a public https host; the endpoint always uses fetchAsset.
export async function buildListing(plot, { fetchMeta = true, fetchImage = fetchAsset } = {}) {
  const notes = [];
  const wanted = (Array.isArray(plot.images) ? plot.images : [])
    .filter((u) => typeof u === 'string' && /^https:\/\//i.test(u)).slice(0, IMAGE_MAX);
  let source = wanted.length ? 'images' : 'none';
  if (!wanted.length && fetchMeta && plot.url) {
    const meta = await fetchSiteMeta(plot.url);
    if (meta?.image) { wanted.push(meta.image); source = 'og:image'; }
    else {
      notes.push(`no og:image on ${plot.url} and no images[] sent — the city will photograph your page and use that; send images[] to choose the picture yourself`);
    }
  }
  const media = {};
  const pictures = [];
  for (const url of wanted) {
    if (pictures.length >= PICTURE_NODES.length) break;
    try {
      const buf = await fetchImage(url, { maxBytes: PICTURE_MAX, label: `image ${pictures.length + 1}` });
      const kind = imageKind(buf);
      if (!kind) { notes.push(`${url} is not a png, jpg or webp — skipped`); continue; }
      const name = `pic-${pictures.length + 1}.${kind}`;
      media[name] = buf.toString('base64');
      pictures.push(name);
    } catch (e) {
      notes.push(`could not fetch ${url}: ${String(e.message || e).slice(0, 80)} — skipped`);
    }
  }

  // The logo. A PNG is extruded into a solid mark on the plinth in the window;
  // anything else can only be read as a flat rectangle, which is not worth a
  // sculpture, so the shop falls back to its monogram and the report says why.
  // That note is the whole mechanism for teaching an agent to send the better
  // asset next time, so it names the format rather than just declining.
  const logoUrl = typeof plot.logo === 'string' && /^https:\/\//i.test(plot.logo) ? plot.logo : null;
  let logoBuf = null;
  if (logoUrl) {
    try {
      const buf = await fetchImage(logoUrl, { maxBytes: LOGO_MAX, label: 'logo' });
      if (imageKind(buf) === 'png') logoBuf = buf;
      else notes.push(`logo ${logoUrl} is not a png — the 3D mark on the plinth is built from a png's transparency, so the shop is using its monogram instead`);
    } catch (e) {
      notes.push(`could not fetch logo ${logoUrl}: ${String(e.message || e).slice(0, 80)} — skipped`);
    }
  }

  // one picture goes on the facade AND the wall facing the door
  const bound = pictures.length === 1 ? [pictures[0], pictures[0]] : pictures;
  const colors = resolveColors(plot);
  const t = buildTemplate({
    slug: plot.slug,
    category: plot.category,
    color: colors.accent,
    primaryColor: colors.primary,
    images: bound.length,
    name: plot.name || '',
    tagline: plot.tagline || '',
    builder: plot.builder || '',
    url: plot.url || '',
    logo: logoBuf,
  });
  const glb = await t.write();
  if (logoBuf && !t.logo) {
    notes.push('the logo could not be read as a mark — too sparse, or the whole square was ink once thresholded; the shop is using its monogram');
  }
  delete plot.images;
  delete plot.logo;
  delete plot.colors;
  plot.media = { ...(plot.media || {}), pictures: bound.map((file, i) => ({ node: PICTURE_NODES[i], file: `media/${file}` })) };
  if (!plot.media.pictures.length) delete plot.media.pictures;
  if (!Object.keys(plot.media).length) delete plot.media;
  plot.anims = t.anims;
  if (!plot.color) plot.color = t.color;
  // What the city derived, so a later version of the template can rebuild this
  // exact shop: the sources it used, and the logo url it read (the mark itself
  // is baked into the glb, not stored).
  plot.template = {
    id: TEMPLATE_ID,
    version: TEMPLATE_VERSION,
    variant: t.variant,
    pictures: source,
    logo: t.logo ? 'voxel' : 'monogram',
    ...(logoUrl ? { logo_url: logoUrl } : {}),
    ...(colors.primary ? { primary: colors.primary } : {}),
  };
  return { glb, media, variant: t.variant, pictures: pictures.length, source, logo: t.logo, notes };
}

// Is anybody else already standing on this identity? Advisory only: one owner
// with two genuine projects is legitimate, and the city's own lots all share
// otra.city. It is here because the likeliest cause by far is an agent that
// hit a failure and retried under a fresh slug, which quietly costs it a
// second lot and leaves the first one dead. Read from the deployed manifest,
// so it lags a merge by a minute — which is exactly why it never rejects.
async function checkDuplicateOwner(slug, url, host) {
  try {
    let manifest;
    if (/^(localhost|127\.0\.0\.1)/.test(host)) {
      manifest = JSON.parse(readFileSync(new URL('../public/plots/index.json', import.meta.url), 'utf8'));
    } else {
      const r = await fetch(`https://${host}/plots/index.json`, { headers: { 'user-agent': 'otra-city-bot/1.0' } });
      if (!r.ok) return null;
      manifest = await r.json();
    }
    const mine = ownerKey(url);
    const others = (manifest.lots || [])
      .filter((l) => l.slug && l.slug !== slug && l.url && ownerKey(l.url) === mine);
    if (!others.length) return null;
    return { ok: true, warn: true, detail:
      `${mine} already holds ${others.map((o) => `"${o.slug}" (${o.address || o.lot})`).join(', ')}. ` +
      `If this is the same project under a new name, resubmit that slug instead — it updates in place and ` +
      `keeps its address. A second lot is yours if you meant it; nobody will take the first one back.` };
  } catch { return null; }
}

async function gh(path, method, body, token) {
  const r = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      accept: 'application/vnd.github+json',
      'user-agent': 'otra-city-bot/1.0',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!r.ok) {
    const err = new Error(`${method} ${path} -> ${r.status}: ${(await r.text()).slice(0, 300)}`);
    err.status = r.status;
    throw err;
  }
  return r.json();
}

// Contents writes right after a ref is created can 409 while GitHub settles
// the new branch; 5xx are plain transients. Both are worth a couple of retries.
async function ghRetry(path, method, body, token, tries = 3) {
  for (let i = 1; ; i++) {
    try {
      return await gh(path, method, body, token);
    } catch (e) {
      if (i >= tries || !(e.status === 409 || e.status >= 500)) throw e;
      await new Promise((r) => setTimeout(r, 1500 * i));
    }
  }
}

// GET that treats 404 as null (missing file/dir) instead of throwing.
async function ghMaybe(path, token) {
  const r = await fetch(`https://api.github.com${path}`, {
    headers: { authorization: `Bearer ${token}`, accept: 'application/vnd.github+json', 'user-agent': 'otra-city-bot/1.0' },
  });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`GET ${path} -> ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}

// Every file currently under a plot folder on a ref, with the blob shas the
// contents API needs for updates and deletes.
async function listPlotFiles(repo, dir, ref, token) {
  const items = await ghMaybe(`/repos/${repo}/contents/${dir}?ref=${encodeURIComponent(ref)}`, token);
  if (!Array.isArray(items)) return [];
  const out = [];
  for (const it of items) {
    if (it.type === 'file') out.push({ path: it.path, sha: it.sha });
    else if (it.type === 'dir') out.push(...await listPlotFiles(repo, it.path, ref, token));
  }
  return out;
}

// Ownership: a slug can only be UPDATED by the identity that owns it. Without
// this, any trusted domain (which skips the backlink) could overwrite anyone.
async function existingManifest(slug, host) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (token && repo) {
    // the repo is the source of truth; the deployed site lags a merge by a minute
    const f = await ghMaybe(`/repos/${repo}/contents/public/plots/${slug}/plot.json?ref=main`, token);
    return f ? JSON.parse(Buffer.from(f.content, 'base64').toString()) : null;
  }
  // A local harness (scripts/dev-api.mjs, scripts/api-check.mjs) answers from
  // the checkout it runs in, exactly as registryOnFile does below — otherwise
  // running the endpoint locally silently validates against production, and a
  // test of who owns what depends on what happens to be deployed.
  if (/^(localhost|127\.0\.0\.1)/.test(host)) {
    const f = new URL(`../public/plots/${slug}/plot.json`, import.meta.url);
    try { return JSON.parse(readFileSync(f, 'utf8')); } catch { return null; }
  }
  const r = await fetch(`https://${host}/plots/${slug}/plot.json`, { headers: { 'user-agent': 'otra-city-bot/1.0' } });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`registry ${r.status}`);
  return r.json();
}

// The land registry on file (slug -> lot id): the repo when there is a token,
// the deployed copy otherwise.
async function registryOnFile(host) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (token && repo) {
    const f = await ghMaybe(`/repos/${repo}/contents/public/plots/lots.json?ref=main`, token);
    return f ? JSON.parse(Buffer.from(f.content, 'base64').toString()).lots || {} : {};
  }
  // a local harness (scripts/dev-api.mjs) answers from the checkout it runs
  // in, so a dry run here reflects the registry beside it, not the deploy's
  if (/^(localhost|127\.0\.0\.1)/.test(host)) {
    return JSON.parse(readFileSync(new URL('../public/plots/lots.json', import.meta.url))).lots || {};
  }
  const r = await fetch(`https://${host}/plots/lots.json`, { headers: { 'user-agent': 'otra-city-bot/1.0' } });
  if (!r.ok) throw new Error(`registry ${r.status}`);
  return (await r.json()).lots || {};
}

// Where the plot would stand. A requested lot (`lot` in plot.json) is yours
// when the map affords it and nobody holds it; a plot that already exists
// keeps its address whatever it asks for; with no request you get the nearest
// free lot to the city centre — named here, so an agent knows before it
// commits. A lot that is held or unknown is a rejection HERE, where the
// agent can fix it; a lot taken in the minute between this check and CI's
// allocation falls back to the nearest free lot, and the status endpoint
// says which (see docs/submission.md).
async function checkLot(plot, ownership, host) {
  try {
    const registry = await registryOnFile(host);
    const held = new Map(Object.entries(registry).map(([slug, id]) => [id, slug]));
    const want = plot.lot;
    const has = (id) => PLAT.lots[id];
    const addr = (id) => `${id} (${has(id)?.address ?? '?'})`;
    if (ownership?.mode === 'update' && registry[plot.slug]) {
      const id = registry[plot.slug];
      return { ok: true, mode: 'kept', lot: id,
        detail: `this plot keeps its address, ${addr(id)}; a plot never moves` +
          (want && want !== id ? ` — "${want}" ignored` : '') };
    }
    // The city's own plots — exhibitions, venues, demos — are placed by hand;
    // a listing is placed by its category, so a street reads as one kind of
    // thing. Same function CI allocates with, so this line is a prediction
    // that comes true (unless the lot goes in the minute between, in which
    // case the next one on the same road does, and the status endpoint says).
    const mayRequest = apexHost(plot.url || '') === 'otra.city';
    const category = plot.category || DEFAULT_CATEGORY;
    const pick = pickLot(PLAT, held.keys(), { category, requested: want, mayRequest, centre: PLAT.centre });
    if (!pick) return { ok: false, mode: 'full', lot: null, detail: 'no free lot left on the map — open an issue' };
    if (want && !mayRequest) {
      // a wrong id is still a wrong id, and worth a rejection so the agent
      // learns the rule here rather than wondering why it was ignored
      if (typeof want !== 'string' || !has(want)) {
        return { ok: false, mode: 'unknown', lot: null,
          detail: `"${want}" is not a lot on the map — and a listing does not pick one: drop "lot" and you land on ${addr(pick.id)}, the first free lot on a road serving ${category}` };
      }
    }
    if (mayRequest && want && pick.why !== 'requested') {
      if (typeof want !== 'string' || !has(want)) {
        return { ok: false, mode: 'unknown', lot: null,
          detail: `"${want}" is not a lot on the map — pick an id from GET /api/plots vacant[] (or drop it for ${addr(pick.id)})` };
      }
      return { ok: false, mode: 'held', lot: null,
        detail: `${addr(want)} is held by ${held.get(want)} — pick another from GET /api/plots vacant[] (or drop it for ${addr(pick.id)})` };
    }
    const road = PLAT.roads?.[has(pick.id)?.road];
    const detail = {
      requested: `${addr(pick.id)} is free — yours if it still is when CI allocates, about a minute from now; otherwise the next lot the same rule gives, and GET /api/plots/${plot.slug} reports which`,
      category: `${addr(pick.id)} on ${road?.name ?? pick.id}, the road for ${category}` +
        (want ? ` — "${want}" ignored: a listing is placed by its category, not by request` : ''),
      'category-full': `every lot on the roads serving ${category} is held, so ${addr(pick.id)}, the nearest free lot — the city grows a road for ${category} when this happens`,
      'category-unrouted': `no road serves "${category}" yet, so ${addr(pick.id)}, the nearest free lot`,
      nearest: `${addr(pick.id)}, the nearest free lot to the centre`,
    }[pick.why];
    return { ok: true, mode: pick.why, lot: pick.id, detail };
  } catch (e) {
    return { ok: false, mode: 'unknown', lot: null, detail: `lot check failed: ${e.name || e}` };
  }
}

async function checkOwnership(slug, url, host) {
  try {
    const existing = await existingManifest(slug, host);
    if (!existing) return { ok: true, mode: 'create', detail: 'new slug' };
    // ownerKey, not the bare hostname: on a multi-tenant host it carries the
    // tenant, so github.com/alice cannot overwrite github.com/bob.
    const owner = ownerKey(existing.url);
    const mine = ownerKey(url);
    return owner === mine
      ? { ok: true, mode: 'update', detail: `updating your existing plot — ${owner} is your identity; keep it or you lose write access to this slug` }
      : { ok: false, mode: 'denied', detail: `slug "${slug}" belongs to ${owner}; updates must come from there (the url is the owner's identity)` };
  } catch (e) {
    return { ok: false, mode: 'unknown', detail: `ownership check failed: ${e.name || e}` };
  }
}

// Dry-run visibility into what a real submit would do on GitHub, so
// "accepted" means "would land": token works, and create vs replace.
async function checkGithub(slug) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (!token || !repo) return { ok: true, mode: 'dry-only', detail: 'no bot token on this deployment — validation only' };
  try {
    if (!(await ghMaybe(`/repos/${repo}`, token))) return { ok: false, detail: 'bot token cannot see the repo' };
    const existing = await listPlotFiles(repo, `public/plots/${slug}`, 'main', token);
    return existing.length
      ? { ok: true, mode: 'update', detail: `will REPLACE the existing plot wholesale (${existing.length} files on main; stale media removed)` }
      : { ok: true, mode: 'create', detail: 'will create the plot' };
  } catch (e) {
    return { ok: false, detail: `github check failed: ${e.message}` };
  }
}

async function createPR({ plot, glb, media }, report) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  const base = 'main';
  const branch = `plot/${plot.slug}-${Date.now().toString(36)}`;
  const ref = await gh(`/repos/${repo}/git/ref/heads/${base}`, 'GET', null, token);
  await gh(`/repos/${repo}/git/refs`, 'POST', { ref: `refs/heads/${branch}`, sha: ref.object.sha }, token);
  try {
    const dir = `public/plots/${plot.slug}`;
    // existing blob shas: required by the contents API for updates/deletes
    const existing = new Map((await listPlotFiles(repo, dir, branch, token)).map((f) => [f.path, f.sha]));
    const files = {
      [`${dir}/plot.json`]: Buffer.from(JSON.stringify(plot, null, 2)).toString('base64'),
      [`${dir}/plot.glb`]: glb.toString('base64'),
    };
    for (const [name, b64] of Object.entries(media || {})) files[`${dir}/media/${name}`] = b64;
    for (const [path, content] of Object.entries(files)) {
      const body = { message: `plot: ${plot.slug} ${path.split('/').pop()}`, content, branch };
      if (existing.has(path)) body.sha = existing.get(path);
      await ghRetry(`/repos/${repo}/contents/${path}`, 'PUT', body, token);
    }
    // wholesale replacement: anything on the old plot not in this bundle goes
    for (const [path, sha] of existing) {
      if (!(path in files)) {
        await ghRetry(`/repos/${repo}/contents/${path}`, 'DELETE', { message: `plot: ${plot.slug} remove stale ${path.split('/').pop()}`, sha, branch }, token);
      }
    }
    const pr = await gh(`/repos/${repo}/pulls`, 'POST', {
      title: `plot: ${existing.size ? 'update ' : ''}${plot.name} (${plot.slug})`,
      head: branch,
      base,
      body: `Automated plot submission via /api/plots/submit\n\n\`\`\`\n${report}\n\`\`\`\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)`,
    }, token);
    return pr.html_url;
  } catch (e) {
    // never leave a zero-diff branch behind
    await fetch(`https://api.github.com/repos/${repo}/git/refs/heads/${branch}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${token}`, 'user-agent': 'otra-city-bot/1.0' },
    }).catch(() => {});
    throw e;
  }
}

// --- Submission telemetry -------------------------------------------------
// Every attempt prints ONE structured line, accepted or not. The REJECTIONS
// are the half that used to vanish entirely, and they are the denominator:
// without them "submissions went up" cannot be told apart from "submissions
// started passing", and the one genuinely interesting question about this city
// — what an agent gets done end to end with no human in the loop — becomes
// unanswerable a month after the fact. PromptFrenzy's directory shipped
// without this, watched its submission rate go up 5x, and could not say why.
//
// Deliberately stdout and nothing else: no database, no third party, no
// cookie, and nothing on this path that can fail in a way that costs an honest
// agent its plot. Retention is therefore the platform's log retention; a log
// drain is the upgrade when there is something worth keeping.
//
// Kept: the request's own metadata. NOT kept: the bundle, and no IP address —
// Vercel's country header is as fine-grained as this gets. The published
// contract at /claim lists these fields; adding one here means adding it there
// in the same commit.
const CALLER_HEADERS = ['user-agent', 'origin', 'referer', 'content-type',
  'sec-fetch-mode', 'sec-fetch-site', 'x-vercel-ip-country'];

function logAttempt(req, fields) {
  try {
    const caller = {};
    for (const h of CALLER_HEADERS) {
      const v = req.headers?.[h];
      if (v) caller[h] = String(v).slice(0, 200);
    }
    console.log('SUBMIT ' + JSON.stringify({ at: new Date().toISOString(), ...fields, caller }));
  } catch { /* telemetry must never be what fails a submission */ }
}

// The named checks that did not pass — what to fix, in one field, so a run of
// rejections reads as a pattern rather than a pile of reports.
const ADVISORY = new Set(['surfaces.coplanar faces', 'payload']); // reported, never blocking

function failedChecks(result) {
  const out = [];
  for (const [section, value] of Object.entries(result)) {
    if (!value || typeof value !== 'object') continue;
    if (Array.isArray(value.checks)) {
      for (const c of value.checks) if (c && c.ok === false) out.push(`${section}.${c.name}`);
    } else if (value.ok === false) {
      out.push(section);
    }
  }
  return out.filter((n) => !ADVISORY.has(n));
}

export default async function handler(req, res) {
  res.setHeader('content-type', 'application/json');
  if (req.method !== 'POST') {
    logAttempt(req, { outcome: 'wrong-method', method: req.method });
    res.statusCode = 405;
    res.end(JSON.stringify({ error: 'POST a submission bundle; see https://otra.city/docs/submission.md' }));
    return;
  }
  const started = Date.now();
  try {
    const { body, bytes: requestBytes } = await readBody(req);
    const plot = body.plot || {};
    // telemetry-only fields never travel into the plot that gets published
    delete plot.discovery_source;
    const listing = !body.glb_base64 && !body.glb_url;
    prepareListing(plot, listing);
    const result = { spec_version: SPEC.version, identity: null, budgets: null, walkability: null, backlink: null };

    result.identity = validateIdentity(plot);

    // Two ways to hand over the files. Inline base64 is simplest and is capped
    // by the platform's request-body limit; urls are fetched server-side under
    // the same per-file caps, which is the only way to spend the full media
    // budget. They can be mixed.
    let fetchedBytes = 0;
    let glb;
    let built = null;
    if (body.glb_base64) {
      glb = Buffer.from(body.glb_base64, 'base64');
    } else if (body.glb_url) {
      glb = await fetchAsset(body.glb_url, { maxBytes: SPEC.budgets.max_glb_bytes, label: 'glb' });
      fetchedBytes += glb.length;
    } else {
      // No build: a listing. The city builds the shopfront; the site is only
      // read for its pictures when the identity is sound, so a malformed
      // submission costs nobody a fetch.
      built = await buildListing(plot, { fetchMeta: result.identity.ok });
      glb = built.glb;
      for (const b64 of Object.values(built.media)) fetchedBytes += Buffer.from(b64, 'base64').length;
    }
    const requireDoor = plot.type === 'shop';
    result.budgets = await validateGlb(glb, { requireDoor });
    delete result.budgets.doc;
    result.walkability = await probeWalkability(glb, { door: requireDoor });
    // Surface hygiene. Coincident faces are ADVISORY: ingest separates them on
    // merge, so they never reach a visitor — reported so you can fix the source.
    // Media UVs are not fixable at ingest (only you know what the quad framed),
    // so a video mapped to an atlas cell is a rejection.
    result.surfaces = await probeSurfaces(glb, { plot });

    const media = { ...(body.media || {}), ...(built?.media || {}) };
    for (const [name, src] of Object.entries(body.media_urls || {})) {
      if (name in media) {
        throw new Error(`media "${name}" was sent twice — once inline and once in media_urls; pick one`);
      }
      if (!/^[a-z0-9._-]+$/i.test(name)) {
        throw new Error(`media "${name}": the key is the filename and must be [a-z0-9._-]`);
      }
      const cap = MEDIA_MAX[name.split('.').pop().toLowerCase()];
      if (!cap) throw new Error(`media "${name}": that extension is not an accepted media type`);
      const buf = await fetchAsset(src, { maxBytes: cap, label: `media ${name}` });
      media[name] = buf.toString('base64');
      fetchedBytes += buf.length;
    }

    const mediaChecks = [];
    let mediaOk = true;
    let screenBytes = 0;
    const buffers = {};
    for (const [name, b64] of Object.entries(media)) {
      const ext = name.split('.').pop().toLowerCase();
      const buf = Buffer.from(b64, 'base64');
      const size = buf.length;
      buffers[name] = buf;
      const cap = MEDIA_MAX[ext];
      const ok = !!cap && size <= cap && /^[a-z0-9._-]+$/i.test(name);
      if (ext === 'mp4') screenBytes += size;
      mediaOk &&= ok;
      mediaChecks.push({
        name: `media ${name}`,
        ok,
        detail: ok ? `${KiB(size)} ${ext}`
          : !cap ? `${KiB(size)} — .${ext} is not an accepted media type`
            : size > cap ? `${KiB(size)} — over the ${KiB(cap)} cap for .${ext}`
              : `${KiB(size)} — filename must be [a-z0-9._-]`,
      });
    }
    // The screens budget is a TOTAL across both videos, which the per-file
    // ceiling above cannot express.
    if (screenBytes) {
      const ok = screenBytes <= SCREENS_TOTAL;
      mediaOk &&= ok;
      mediaChecks.push({ name: 'screens total', ok,
        detail: `${KiB(screenBytes)} of ${KiB(SCREENS_TOTAL)} across all mp4 screens` });
    }
    const decl = validateMediaDecl(plot, Object.keys(media));
    mediaChecks.push(...decl.checks);
    mediaOk &&= decl.ok;
    // Duration and resolution — the caps the docs published and nothing read.
    const probes = probeMediaFiles(plot, buffers);
    mediaChecks.push(...probes.checks);
    mediaOk &&= probes.ok;
    result.media = { checks: mediaChecks, ok: mediaOk };

    if (plot.media?.feed) result.feed = await checkFeed(plot.media.feed, media);
    const host = req.headers['x-forwarded-host'] || req.headers.host || 'otra.city';
    if (result.identity.ok) {
      // Derived live from the url and never stored, so the lists behind it
      // re-classify every future submission with nothing to backfill.
      result.url = classifyUrl(plot.url);
      result.backlink = await checkBacklink(plot.url, plot.slug);
      result.ownership = await checkOwnership(plot.slug, plot.url, host);
      result.github = await checkGithub(plot.slug);
      result.lot = await checkLot(plot, result.ownership, host);
      result.duplicate = await checkDuplicateOwner(plot.slug, plot.url, host);
    }

    const uvCheck = result.surfaces.checks.find((c) => c.name === 'media uvs');
    const accepted = result.identity.ok && result.budgets.ok && result.walkability.ok &&
      mediaOk && uvCheck.ok && (result.feed ? result.feed.ok : true) && !!result.backlink?.ok &&
      !!result.ownership?.ok && !!result.github?.ok && !!result.lot?.ok && !!result.url?.ok;
    const lines = [];
    for (const section of ['identity', 'budgets', 'walkability', 'media']) {
      for (const c of result[section].checks) lines.push(`${c.ok ? 'PASS' : 'FAIL'}  ${c.name.padEnd(14)} ${c.detail}`);
    }
    for (const c of result.surfaces.checks) {
      const advisory = c.name === 'coplanar faces';
      lines.push(`${c.ok ? 'PASS' : advisory ? 'WARN' : 'FAIL'}  ${c.name.padEnd(14)} ${c.detail}` +
        (c.ok || !advisory ? '' : ' [separated at ingest — fix your source to see it as you built it]'));
    }
    // Advisory: a submission that got this far is already inside the limit.
    // It is here so the next, larger bundle is a budget rather than a mystery.
    result.payload = {
      bytes: requestBytes,
      limit_bytes: REQUEST_BODY_LIMIT,
      ok: requestBytes <= REQUEST_BODY_LIMIT * 0.9,
    };
    result.payload.fetched_bytes = fetchedBytes;
    lines.push(`${result.payload.ok ? 'PASS' : 'WARN'}  payload        ` +
      `${MB(requestBytes)} of ${MB(REQUEST_BODY_LIMIT)} request body` +
      (fetchedBytes ? ` + ${MB(fetchedBytes)} fetched by url (not subject to the limit)` : '') +
      (result.payload.ok ? '' : ' — close to the platform limit; send large files by url instead'));
    if (result.feed) lines.push(`${result.feed.ok ? 'PASS' : 'FAIL'}  live feed      ${result.feed.detail}`);
    if (built) {
      result.shopfront = { ok: true, template: `${TEMPLATE_ID}/${built.variant}`, version: TEMPLATE_VERSION,
        pictures: built.pictures, source: built.source, logo: built.logo, notes: built.notes };
      lines.push(`PASS  shopfront      built by the city: ${TEMPLATE_ID}/${built.variant} v${TEMPLATE_VERSION}, ` +
        (built.pictures ? `${built.pictures} picture(s) from ${built.source}` : 'no pictures yet') +
        ` — the sign over the door says "${plot.name}"`);
      lines.push(`PASS  logo           ${built.logo
        ? `built as a solid mark on the plinth in the window (${built.logo.boxes} blocks)`
        : 'none — the shop is using its monogram; send `logo` (an https png, ideally with a transparent background) and the city builds it in 3D'}`);
      // The one thing worth saying twice: everything above is a floor, and
      // three optional fields raise it. A listing that reads its own report is
      // the only place this can be taught.
      lines.push('PASS  make it better  send `images` (screenshots), `logo` (png) and `colors` '
        + '{primary, accent} on your next submission — same slug, same host — and the city rebuilds the shop around them');
      for (const n of built.notes) lines.push(`WARN  shopfront      ${n}`);
    }
    // "url host", not "url": validateIdentity already reports a check called
    // `url` (is it a well-formed https address), so labelling this one the same
    // printed "PASS url" and "FAIL url" one after the other and read as a
    // contradiction to anything parsing the report — which is every caller.
    if (result.url) lines.push(`${result.url.ok ? 'PASS' : 'FAIL'}  url host       ${result.url.detail}`);
    if (result.backlink) lines.push(`${result.backlink.ok ? 'PASS' : 'FAIL'}  backlink       ${result.backlink.detail}`);
    if (result.ownership) lines.push(`${result.ownership.ok ? 'PASS' : 'FAIL'}  ownership      ${result.ownership.detail}`);
    if (result.github) lines.push(`${result.github.ok ? 'PASS' : 'FAIL'}  github         ${result.github.detail}`);
    if (result.lot) lines.push(`${result.lot.ok ? 'PASS' : 'FAIL'}  lot            ${result.lot.detail}`);
    if (result.duplicate) lines.push(`WARN  duplicate      ${result.duplicate.detail}`);
    const report = lines.join('\n') + `\nVERDICT: ${accepted ? 'ACCEPTED' : 'REJECTED'}`;

    let pr_url = null;
    const dry = body.dry === true || !process.env.GITHUB_TOKEN || !process.env.GITHUB_REPO;
    if (accepted && !dry) pr_url = await createPR({ plot, glb, media }, report);

    logAttempt(req, {
      outcome: accepted ? (dry ? 'accepted-dry' : 'accepted') : 'rejected',
      slug: plot.slug ?? null,
      owner: plot.url ? ownerKey(plot.url) : null,
      url_tier: result.url?.tier ?? null,
      builder: typeof plot.builder === 'string' ? plot.builder.slice(0, 120) : null,
      lot: result.lot?.lot ?? null,
      mode: result.github?.mode ?? null,
      // how the files arrived: the by-url path is the only way to spend the
      // full media budget, so its uptake is worth watching; `template` is a
      // listing the city built for
      transport: body.glb_url ? 'url' : body.glb_base64 ? 'inline' : 'template',
      category: plot.category ?? null,
      // one optional free-text field: how the submitter found the city.
      // Unverified, capped, never stored on the plot — it is the only way to
      // tell a repeatable channel from a one-off.
      discovery_source: typeof body.discovery_source === 'string' ? body.discovery_source.slice(0, 120) : null,
      media_by_url: Object.keys(body.media_urls || {}).length,
      request_bytes: requestBytes,
      fetched_bytes: fetchedBytes,
      failed: failedChecks(result),
      duplicate_owner: !!result.duplicate,
      ms: Date.now() - started,
    });

    res.statusCode = accepted ? 200 : 422;
    res.end(JSON.stringify({
      accepted,
      dry,
      pr_url,
      permalink: `https://otra.city/s/${plot.slug}`,
      lot: result.lot?.lot ?? null,
      lot_url: result.lot?.lot ? `https://otra.city/lot/${result.lot.lot}` : null,
      build: built ? 'template' : 'custom',
      // the plot.json as it would be published — for a listing, that includes
      // what the city derived: tagline, colour, the pictures it bound, `template`
      plot,
      map: 'https://otra.city/map',
      status_url: `https://otra.city/api/plots/${plot.slug}`,
      embed_url: `https://otra.city/embed?plot=${plot.slug}`,
      preview: 'https://otra.city/preview — drop your glb to see it in the real pipeline',
      report,
      result,
    }, null, 2));
  } catch (e) {
    // Errors are attempts too: a bundle that throws before the checks run
    // (unreadable JSON, a media url that would not fetch, no glb at all) is
    // an agent that tried and got nothing, and it is invisible in the report
    // counts unless it is logged here.
    logAttempt(req, { outcome: 'error', error: String(e.message || e).slice(0, 300), ms: Date.now() - started });
    console.error('submit failed:', e.message || e);
    res.statusCode = 400;
    res.end(JSON.stringify({ error: String(e.message || e) }));
  }
}
