// POST /api/plots/submit — the no-fork submission path (ai-directory model).
// Accepts JSON { plot: {...}, glb_base64 | glb_url,
//                media?: { "name.ext": base64 }, media_urls?: { "name.ext": url } },
// runs the exact published checks, verifies the backlink (unless the domain
// is pre-trusted, e.g. existing PromptFrenzy AI-directory listees), then
// creates the PR with the directory bot's credentials. The submitter needs
// nothing but this one HTTP call.
//
// Env: GITHUB_TOKEN (bot PAT with repo scope), GITHUB_REPO ("owner/name").
// Without a token — or with { dry: true } — it validates and reports only.
import { validateIdentity, validateGlb, probeWalkability, validateMediaDecl, probeSurfaces, probeMediaFiles, SPEC } from '../lib/validate-plot.mjs';
import { fetchAsset } from '../lib/fetch-asset.mjs';
import { rankFree } from '../public/js/city-map.mjs';
import { readFileSync } from 'node:fs';

const TRUSTED = JSON.parse(readFileSync(new URL('../trusted.json', import.meta.url)));
// The plat: every lot the map affords, generated by scripts/build-map.mjs. It
// is read from the deployed bundle, so a lot id is checked against the map
// this deployment was built with; which lots are FREE comes from the registry
// on main, below, because the map changes rarely and the registry every claim.
const PLAT = JSON.parse(readFileSync(new URL('../public/city/lots.json', import.meta.url)));

// Per-file ceilings, read from the SPEC the docs publish rather than repeated
// here. The two had already drifted: the spec caps screens at 16 MiB TOTAL and
// this table was checking 16 MiB PER FILE, so two screens could pass at double
// the published budget. A number that lives in one place cannot drift again.
const SM = SPEC.media;
const AUDIO_MAX = SM.ambient_audio.max_bytes;
const PICTURE_MAX = SM.pictures.max_bytes_each;
const SCREENS_TOTAL = SM.screens.max_bytes_total;
const FEED_JSON_MAX = 64 << 10;              // a bundled live-feed document
const MEDIA_MAX = {
  m4a: AUDIO_MAX, mp3: AUDIO_MAX, ogg: AUDIO_MAX,
  mp4: SCREENS_TOTAL,                        // one screen may spend the whole allowance
  png: PICTURE_MAX, jpg: PICTURE_MAX, jpeg: PICTURE_MAX, webp: PICTURE_MAX,
  json: FEED_JSON_MAX,
};

// The platform rejects a request body over this BEFORE the function runs: a
// bare text/plain 413, no JSON, no report, nothing this code can catch or
// explain. Base64 inflates every file by a third on the way in, so the real
// ceiling for an inline bundle is ~3.3 MB of actual bytes — well under the sum
// of the published per-file caps. Bundles that big must come in by URL.
const REQUEST_BODY_LIMIT = 4.5e6;
const MB = (n) => `${(n / 1e6).toFixed(2)} MB`;
const KiB = (n) => `${(n / 1024).toFixed(0)} KiB`;

// What the panel renderer can actually draw. Measured in the real 512x384
// canvas with the fonts renderFeed uses, at the x each string starts from:
// these are the lengths at which text runs off the panel, not a style guide.
const PANEL = { big: 8, title: 28, sub: 33, bars: 16 };

// The old check asked only whether one of the four keys existed, so a feed
// whose bars were strings passed the dry run and then drew an empty chart on
// the lot. Type errors fail here; things that merely won't fit are reported in
// the detail, because a clipped headline is the author's call, not a defect.
function feedShape(d) {
  if (!d || typeof d !== 'object' || Array.isArray(d)) {
    return { ok: false, why: 'is not a JSON object' };
  }
  if (!['title', 'big', 'sub', 'bars'].some((k) => k in d)) {
    return { ok: false, why: 'has none of title, big, sub, bars' };
  }
  for (const k of ['title', 'big', 'sub']) {
    const v = d[k];
    if (k in d && v !== null && typeof v !== 'string' && typeof v !== 'number') {
      return { ok: false, why: `${k} must be a string or number (got ${Array.isArray(v) ? 'array' : typeof v})` };
    }
  }
  const notes = [];
  if ('bars' in d) {
    if (!Array.isArray(d.bars)) {
      return { ok: false, why: `bars must be an array of plain numbers (got ${typeof d.bars})` };
    }
    const bad = d.bars.filter((b) => typeof b !== 'number' || !Number.isFinite(b)).length;
    if (bad) {
      return { ok: false, why: `${bad} of ${d.bars.length} bars are not finite numbers — those draw nothing` };
    }
    if (d.bars.length > PANEL.bars) notes.push(`${d.bars.length} bars, only the first ${PANEL.bars} are drawn`);
  }
  for (const [k, max] of [['big', PANEL.big], ['title', PANEL.title], ['sub', PANEL.sub]]) {
    const len = String(d[k] ?? '').length;
    if (len > max) notes.push(`${k} is ${len} chars, ~${max} fit on the panel`);
  }
  return { ok: true, notes };
}

const CITY_ORIGIN = 'https://otra.city';
const corsOpen = (v) => v === '*' || (v || '').toLowerCase() === CITY_ORIGIN;

// A visitor's browser applies CORS to EVERY hop, so a redirect that does not
// itself carry Access-Control-Allow-Origin stops the fetch dead however open
// the destination is. node's fetch follows redirects with no CORS at all, so
// walking them by hand is the only way this check can mean what it says —
// otherwise a plot passes the dry run and its panel never leaves the fallback
// texture in the real city. (Found exactly this on a live plot.)
async function fetchLikeABrowser(url, maxHops = 3) {
  let current = url;
  for (let hop = 0; ; hop++) {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 8000);
    const r = await fetch(current, {
      signal: ctl.signal,
      redirect: 'manual',
      headers: { 'user-agent': 'otra-city-bot/1.0', origin: CITY_ORIGIN },
    });
    clearTimeout(t);
    const cors = r.headers.get('access-control-allow-origin');
    const location = r.headers.get('location');
    if (r.status >= 300 && r.status < 400 && location) {
      const next = new URL(location, current).href;
      if (!corsOpen(cors)) {
        return { blocked: `${current} answers ${r.status} -> ${next} without "Access-Control-Allow-Origin" ` +
          `on the redirect itself. A browser stops there even though the destination is open, so the panel ` +
          `would never leave its authored texture. Declare ${next} as your feed url, or send the header on the redirect too.` };
      }
      if (hop >= maxHops) return { blocked: `more than ${maxHops} redirects from ${url}` };
      current = next;
      continue;
    }
    return { r, cors, finalUrl: current };
  }
}

// Live-feed dry check: fetch the declared endpoint (or parse the bundled
// file) and validate the shape, so a broken feed fails HERE, not on the lot.
async function checkFeed(feed, media) {
  try {
    if (feed.url) {
      const hop = await fetchLikeABrowser(feed.url);
      if (hop.blocked) return { ok: false, detail: hop.blocked };
      const { r, cors } = hop;
      if (!r.ok) return { ok: false, detail: `GET ${feed.url} -> ${r.status}` };
      const data = await r.json();
      const shape = feedShape(data);
      if (!shape.ok) return { ok: false, detail: `response ${shape.why} — the panel needs {title, big, sub, bars[]}` };
      const fits = shape.notes.length ? ` — note: ${shape.notes.join('; ')}` : '';
      return {
        ok: corsOpen(cors),
        detail: (corsOpen(cors)
          ? `endpoint OK, shape OK, CORS OK (panel falls back to its authored texture if it ever breaks)`
          : `shape OK but missing "Access-Control-Allow-Origin: *" — the browser polls this URL directly, so without CORS the panel will only ever show its authored texture`) + fits,
      };
    }
    const name = (feed.file || '').split('/').pop();
    const b64 = media[name];
    if (!b64) return { ok: false, detail: `bundled feed ${feed.file} not found in media` };
    const data = JSON.parse(Buffer.from(b64, 'base64').toString('utf8'));
    const shape = feedShape(data);
    if (!shape.ok) return { ok: false, detail: `bundled feed ${shape.why} — the panel needs {title, big, sub, bars[]}` };
    return { ok: true,
      detail: `bundled feed OK — update it by resubmitting; upgrade to a live url any time` +
        (shape.notes.length ? ` — note: ${shape.notes.join('; ')}` : '') };
  } catch (e) {
    return { ok: false, detail: `feed check failed: ${e.name || e}` };
  }
}

// Returns the parsed bundle AND the wire size, so the report can tell a
// submitter how close they came to the body limit above — the difference
// between "you have room for a longer video" and a mystery 413 next time.
async function readBody(req) {
  if (req.body) {
    const raw = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
    return { body: typeof req.body === 'string' ? JSON.parse(req.body) : req.body,
      bytes: Buffer.byteLength(raw) };
  }
  const chunks = [];
  for await (const c of req) chunks.push(c);
  const buf = Buffer.concat(chunks);
  return { body: JSON.parse(buf.toString('utf8')), bytes: buf.length };
}

async function checkBacklink(url, slug) {
  const domain = new URL(url).hostname.replace(/^www\./, '');
  if (TRUSTED.domains.includes(domain)) {
    return { ok: true, mode: 'trusted', detail: `${domain} is pre-trusted (existing directory listing)` };
  }
  try {
    const ctl = new AbortController();
    const t = setTimeout(() => ctl.abort(), 8000);
    const r = await fetch(url, { signal: ctl.signal, redirect: 'follow', headers: { 'user-agent': 'otra-city-bot/1.0' } });
    clearTimeout(t);
    if (!r.ok) return { ok: false, mode: 'fetched', detail: `GET ${url} -> ${r.status}` };
    const html = (await r.text()).slice(0, 512 * 1024);
    const needle = `otra.city/s/${slug}`;
    const found = html.includes(needle);
    return {
      ok: found,
      mode: 'fetched',
      detail: found ? `backlink to ${needle} found` : `page does not contain ${needle} — add your plot permalink first`,
    };
  } catch (e) {
    return { ok: false, mode: 'fetched', detail: `could not fetch ${url}: ${e.name}` };
  }
}

async function gh(path, method, body, token) {
  const r = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      accept: 'application/vnd.github+json',
      'user-agent': 'otra-city-bot/1.0',
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!r.ok) {
    const err = new Error(`${method} ${path} -> ${r.status}: ${(await r.text()).slice(0, 300)}`);
    err.status = r.status;
    throw err;
  }
  return r.json();
}

// Contents writes right after a ref is created can 409 while GitHub settles
// the new branch; 5xx are plain transients. Both are worth a couple of retries.
async function ghRetry(path, method, body, token, tries = 3) {
  for (let i = 1; ; i++) {
    try {
      return await gh(path, method, body, token);
    } catch (e) {
      if (i >= tries || !(e.status === 409 || e.status >= 500)) throw e;
      await new Promise((r) => setTimeout(r, 1500 * i));
    }
  }
}

// GET that treats 404 as null (missing file/dir) instead of throwing.
async function ghMaybe(path, token) {
  const r = await fetch(`https://api.github.com${path}`, {
    headers: { authorization: `Bearer ${token}`, accept: 'application/vnd.github+json', 'user-agent': 'otra-city-bot/1.0' },
  });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`GET ${path} -> ${r.status}: ${(await r.text()).slice(0, 200)}`);
  return r.json();
}

// Every file currently under a plot folder on a ref, with the blob shas the
// contents API needs for updates and deletes.
async function listPlotFiles(repo, dir, ref, token) {
  const items = await ghMaybe(`/repos/${repo}/contents/${dir}?ref=${encodeURIComponent(ref)}`, token);
  if (!Array.isArray(items)) return [];
  const out = [];
  for (const it of items) {
    if (it.type === 'file') out.push({ path: it.path, sha: it.sha });
    else if (it.type === 'dir') out.push(...await listPlotFiles(repo, it.path, ref, token));
  }
  return out;
}

const hostOf = (u) => { try { return new URL(u).hostname.replace(/^www\./, ''); } catch { return ''; } };

// Ownership: a slug can only be UPDATED from the domain that owns it. Without
// this, any trusted domain (which skips the backlink) could overwrite anyone.
async function existingManifest(slug, host) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (token && repo) {
    // the repo is the source of truth; the deployed site lags a merge by a minute
    const f = await ghMaybe(`/repos/${repo}/contents/public/plots/${slug}/plot.json?ref=main`, token);
    return f ? JSON.parse(Buffer.from(f.content, 'base64').toString()) : null;
  }
  // tokenless harnesses read the live registry instead
  const origin = /^(localhost|127\.0\.0\.1)/.test(host) ? 'https://otra.city' : `https://${host}`;
  const r = await fetch(`${origin}/plots/${slug}/plot.json`, { headers: { 'user-agent': 'otra-city-bot/1.0' } });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`registry ${r.status}`);
  return r.json();
}

// The land registry on file (slug -> lot id): the repo when there is a token,
// the deployed copy otherwise.
async function registryOnFile(host) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (token && repo) {
    const f = await ghMaybe(`/repos/${repo}/contents/public/plots/lots.json?ref=main`, token);
    return f ? JSON.parse(Buffer.from(f.content, 'base64').toString()).lots || {} : {};
  }
  // a local harness (scripts/dev-api.mjs) answers from the checkout it runs
  // in, so a dry run here reflects the registry beside it, not the deploy's
  if (/^(localhost|127\.0\.0\.1)/.test(host)) {
    return JSON.parse(readFileSync(new URL('../public/plots/lots.json', import.meta.url))).lots || {};
  }
  const r = await fetch(`https://${host}/plots/lots.json`, { headers: { 'user-agent': 'otra-city-bot/1.0' } });
  if (!r.ok) throw new Error(`registry ${r.status}`);
  return (await r.json()).lots || {};
}

// Where the plot would stand. A requested lot (`lot` in plot.json) is yours
// when the map affords it and nobody holds it; a plot that already exists
// keeps its address whatever it asks for; with no request you get the nearest
// free lot to the city centre — named here, so an agent knows before it
// commits. A lot that is held or unknown is a rejection HERE, where the
// agent can fix it; a lot taken in the minute between this check and CI's
// allocation falls back to the nearest free lot, and the status endpoint
// says which (see docs/submission.md).
async function checkLot(plot, ownership, host) {
  try {
    const registry = await registryOnFile(host);
    const held = new Map(Object.entries(registry).map(([slug, id]) => [id, slug]));
    const want = plot.lot;
    const has = (id) => PLAT.lots[id];
    if (ownership?.mode === 'update' && registry[plot.slug]) {
      const id = registry[plot.slug];
      return { ok: true, mode: 'kept', lot: id,
        detail: `this plot keeps its address, ${id} (${has(id)?.address ?? '?'}); a lot request applies to a new plot only` +
          (want && want !== id ? ` — "${want}" ignored` : '') };
    }
    const next = rankFree(PLAT, held.keys(), PLAT.centre)[0];
    if (want === undefined || want === null || want === '') {
      return next
        ? { ok: true, mode: 'default', lot: next.id,
          detail: `none requested — you would get ${next.id} (${next.address}), the first lot on offer; ` +
            `every free lot is in GET /api/plots vacant[], or on https://otra.city/map` }
        : { ok: false, mode: 'full', lot: null, detail: 'no free lot left on the map — open an issue' };
    }
    if (typeof want !== 'string' || !has(want)) {
      return { ok: false, mode: 'unknown', lot: null,
        detail: `"${want}" is not a lot on the map — pick an id from GET /api/plots vacant[] (the nearest free is ${next?.id ?? 'none'})` };
    }
    if (held.has(want)) {
      return { ok: false, mode: 'held', lot: null,
        detail: `${want} (${has(want).address}) is held by ${held.get(want)} — pick another from GET /api/plots vacant[] (the nearest free is ${next?.id ?? 'none'})` };
    }
    return { ok: true, mode: 'requested', lot: want,
      detail: `${want} (${has(want).address}) is free — yours if it still is when CI allocates, about a minute from now; ` +
        `otherwise the nearest free lot, and GET /api/plots/${plot.slug} reports which` };
  } catch (e) {
    return { ok: false, mode: 'unknown', lot: null, detail: `lot check failed: ${e.name || e}` };
  }
}

async function checkOwnership(slug, url, host) {
  try {
    const existing = await existingManifest(slug, host);
    if (!existing) return { ok: true, mode: 'create', detail: 'new slug' };
    const owner = hostOf(existing.url);
    const mine = hostOf(url);
    return owner === mine
      ? { ok: true, mode: 'update', detail: `updating your existing plot — the url host ${owner} is your identity; keep it or you lose write access to this slug` }
      : { ok: false, mode: 'denied', detail: `slug "${slug}" belongs to ${owner}; updates must come from that host (the url host is the owner's identity)` };
  } catch (e) {
    return { ok: false, mode: 'unknown', detail: `ownership check failed: ${e.name || e}` };
  }
}

// Dry-run visibility into what a real submit would do on GitHub, so
// "accepted" means "would land": token works, and create vs replace.
async function checkGithub(slug) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  if (!token || !repo) return { ok: true, mode: 'dry-only', detail: 'no bot token on this deployment — validation only' };
  try {
    if (!(await ghMaybe(`/repos/${repo}`, token))) return { ok: false, detail: 'bot token cannot see the repo' };
    const existing = await listPlotFiles(repo, `public/plots/${slug}`, 'main', token);
    return existing.length
      ? { ok: true, mode: 'update', detail: `will REPLACE the existing plot wholesale (${existing.length} files on main; stale media removed)` }
      : { ok: true, mode: 'create', detail: 'will create the plot' };
  } catch (e) {
    return { ok: false, detail: `github check failed: ${e.message}` };
  }
}

async function createPR({ plot, glb, media }, report) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO;
  const base = 'main';
  const branch = `plot/${plot.slug}-${Date.now().toString(36)}`;
  const ref = await gh(`/repos/${repo}/git/ref/heads/${base}`, 'GET', null, token);
  await gh(`/repos/${repo}/git/refs`, 'POST', { ref: `refs/heads/${branch}`, sha: ref.object.sha }, token);
  try {
    const dir = `public/plots/${plot.slug}`;
    // existing blob shas: required by the contents API for updates/deletes
    const existing = new Map((await listPlotFiles(repo, dir, branch, token)).map((f) => [f.path, f.sha]));
    const files = {
      [`${dir}/plot.json`]: Buffer.from(JSON.stringify(plot, null, 2)).toString('base64'),
      [`${dir}/plot.glb`]: glb.toString('base64'),
    };
    for (const [name, b64] of Object.entries(media || {})) files[`${dir}/media/${name}`] = b64;
    for (const [path, content] of Object.entries(files)) {
      const body = { message: `plot: ${plot.slug} ${path.split('/').pop()}`, content, branch };
      if (existing.has(path)) body.sha = existing.get(path);
      await ghRetry(`/repos/${repo}/contents/${path}`, 'PUT', body, token);
    }
    // wholesale replacement: anything on the old plot not in this bundle goes
    for (const [path, sha] of existing) {
      if (!(path in files)) {
        await ghRetry(`/repos/${repo}/contents/${path}`, 'DELETE', { message: `plot: ${plot.slug} remove stale ${path.split('/').pop()}`, sha, branch }, token);
      }
    }
    const pr = await gh(`/repos/${repo}/pulls`, 'POST', {
      title: `plot: ${existing.size ? 'update ' : ''}${plot.name} (${plot.slug})`,
      head: branch,
      base,
      body: `Automated plot submission via /api/plots/submit\n\n\`\`\`\n${report}\n\`\`\`\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)`,
    }, token);
    return pr.html_url;
  } catch (e) {
    // never leave a zero-diff branch behind
    await fetch(`https://api.github.com/repos/${repo}/git/refs/heads/${branch}`, {
      method: 'DELETE',
      headers: { authorization: `Bearer ${token}`, 'user-agent': 'otra-city-bot/1.0' },
    }).catch(() => {});
    throw e;
  }
}

export default async function handler(req, res) {
  res.setHeader('content-type', 'application/json');
  if (req.method !== 'POST') {
    res.statusCode = 405;
    res.end(JSON.stringify({ error: 'POST a submission bundle; see https://otra.city/docs/submission.md' }));
    return;
  }
  try {
    const { body, bytes: requestBytes } = await readBody(req);
    const plot = body.plot || {};
    const result = { spec_version: SPEC.version, identity: null, budgets: null, walkability: null, backlink: null };

    result.identity = validateIdentity(plot);

    // Two ways to hand over the files. Inline base64 is simplest and is capped
    // by the platform's request-body limit; urls are fetched server-side under
    // the same per-file caps, which is the only way to spend the full media
    // budget. They can be mixed.
    let fetchedBytes = 0;
    let glb;
    if (body.glb_base64) {
      glb = Buffer.from(body.glb_base64, 'base64');
    } else if (body.glb_url) {
      glb = await fetchAsset(body.glb_url, { maxBytes: SPEC.budgets.max_glb_bytes, label: 'glb' });
      fetchedBytes += glb.length;
    } else {
      throw new Error('send your build as glb_base64 (inline, subject to the 4.5 MB request-body limit) ' +
        'or glb_url (an https url the city fetches). See https://otra.city/docs/submission.md');
    }
    const requireDoor = plot.type === 'shop';
    result.budgets = await validateGlb(glb, { requireDoor });
    delete result.budgets.doc;
    result.walkability = await probeWalkability(glb, { door: requireDoor });
    // Surface hygiene. Coincident faces are ADVISORY: ingest separates them on
    // merge, so they never reach a visitor — reported so you can fix the source.
    // Media UVs are not fixable at ingest (only you know what the quad framed),
    // so a video mapped to an atlas cell is a rejection.
    result.surfaces = await probeSurfaces(glb, { plot });

    const media = { ...(body.media || {}) };
    for (const [name, src] of Object.entries(body.media_urls || {})) {
      if (name in media) {
        throw new Error(`media "${name}" was sent twice — once inline and once in media_urls; pick one`);
      }
      if (!/^[a-z0-9._-]+$/i.test(name)) {
        throw new Error(`media "${name}": the key is the filename and must be [a-z0-9._-]`);
      }
      const cap = MEDIA_MAX[name.split('.').pop().toLowerCase()];
      if (!cap) throw new Error(`media "${name}": that extension is not an accepted media type`);
      const buf = await fetchAsset(src, { maxBytes: cap, label: `media ${name}` });
      media[name] = buf.toString('base64');
      fetchedBytes += buf.length;
    }

    const mediaChecks = [];
    let mediaOk = true;
    let screenBytes = 0;
    const buffers = {};
    for (const [name, b64] of Object.entries(media)) {
      const ext = name.split('.').pop().toLowerCase();
      const buf = Buffer.from(b64, 'base64');
      const size = buf.length;
      buffers[name] = buf;
      const cap = MEDIA_MAX[ext];
      const ok = !!cap && size <= cap && /^[a-z0-9._-]+$/i.test(name);
      if (ext === 'mp4') screenBytes += size;
      mediaOk &&= ok;
      mediaChecks.push({
        name: `media ${name}`,
        ok,
        detail: ok ? `${KiB(size)} ${ext}`
          : !cap ? `${KiB(size)} — .${ext} is not an accepted media type`
            : size > cap ? `${KiB(size)} — over the ${KiB(cap)} cap for .${ext}`
              : `${KiB(size)} — filename must be [a-z0-9._-]`,
      });
    }
    // The screens budget is a TOTAL across both videos, which the per-file
    // ceiling above cannot express.
    if (screenBytes) {
      const ok = screenBytes <= SCREENS_TOTAL;
      mediaOk &&= ok;
      mediaChecks.push({ name: 'screens total', ok,
        detail: `${KiB(screenBytes)} of ${KiB(SCREENS_TOTAL)} across all mp4 screens` });
    }
    const decl = validateMediaDecl(plot, Object.keys(media));
    mediaChecks.push(...decl.checks);
    mediaOk &&= decl.ok;
    // Duration and resolution — the caps the docs published and nothing read.
    const probes = probeMediaFiles(plot, buffers);
    mediaChecks.push(...probes.checks);
    mediaOk &&= probes.ok;
    result.media = { checks: mediaChecks, ok: mediaOk };

    if (plot.media?.feed) result.feed = await checkFeed(plot.media.feed, media);
    const host = req.headers['x-forwarded-host'] || req.headers.host || 'otra.city';
    if (result.identity.ok) {
      result.backlink = await checkBacklink(plot.url, plot.slug);
      result.ownership = await checkOwnership(plot.slug, plot.url, host);
      result.github = await checkGithub(plot.slug);
      result.lot = await checkLot(plot, result.ownership, host);
    }

    const uvCheck = result.surfaces.checks.find((c) => c.name === 'media uvs');
    const accepted = result.identity.ok && result.budgets.ok && result.walkability.ok &&
      mediaOk && uvCheck.ok && (result.feed ? result.feed.ok : true) && !!result.backlink?.ok &&
      !!result.ownership?.ok && !!result.github?.ok && !!result.lot?.ok;
    const lines = [];
    for (const section of ['identity', 'budgets', 'walkability', 'media']) {
      for (const c of result[section].checks) lines.push(`${c.ok ? 'PASS' : 'FAIL'}  ${c.name.padEnd(14)} ${c.detail}`);
    }
    for (const c of result.surfaces.checks) {
      const advisory = c.name === 'coplanar faces';
      lines.push(`${c.ok ? 'PASS' : advisory ? 'WARN' : 'FAIL'}  ${c.name.padEnd(14)} ${c.detail}` +
        (c.ok || !advisory ? '' : ' [separated at ingest — fix your source to see it as you built it]'));
    }
    // Advisory: a submission that got this far is already inside the limit.
    // It is here so the next, larger bundle is a budget rather than a mystery.
    result.payload = {
      bytes: requestBytes,
      limit_bytes: REQUEST_BODY_LIMIT,
      ok: requestBytes <= REQUEST_BODY_LIMIT * 0.9,
    };
    result.payload.fetched_bytes = fetchedBytes;
    lines.push(`${result.payload.ok ? 'PASS' : 'WARN'}  payload        ` +
      `${MB(requestBytes)} of ${MB(REQUEST_BODY_LIMIT)} request body` +
      (fetchedBytes ? ` + ${MB(fetchedBytes)} fetched by url (not subject to the limit)` : '') +
      (result.payload.ok ? '' : ' — close to the platform limit; send large files by url instead'));
    if (result.feed) lines.push(`${result.feed.ok ? 'PASS' : 'FAIL'}  live feed      ${result.feed.detail}`);
    if (result.backlink) lines.push(`${result.backlink.ok ? 'PASS' : 'FAIL'}  backlink       ${result.backlink.detail}`);
    if (result.ownership) lines.push(`${result.ownership.ok ? 'PASS' : 'FAIL'}  ownership      ${result.ownership.detail}`);
    if (result.github) lines.push(`${result.github.ok ? 'PASS' : 'FAIL'}  github         ${result.github.detail}`);
    if (result.lot) lines.push(`${result.lot.ok ? 'PASS' : 'FAIL'}  lot            ${result.lot.detail}`);
    const report = lines.join('\n') + `\nVERDICT: ${accepted ? 'ACCEPTED' : 'REJECTED'}`;

    let pr_url = null;
    const dry = body.dry === true || !process.env.GITHUB_TOKEN || !process.env.GITHUB_REPO;
    if (accepted && !dry) pr_url = await createPR({ plot, glb, media }, report);

    res.statusCode = accepted ? 200 : 422;
    res.end(JSON.stringify({
      accepted,
      dry,
      pr_url,
      permalink: `https://otra.city/s/${plot.slug}`,
      lot: result.lot?.lot ?? null,
      map: 'https://otra.city/map',
      status_url: `https://otra.city/api/plots/${plot.slug}`,
      embed_url: `https://otra.city/embed?plot=${plot.slug}`,
      preview: 'https://otra.city/preview — drop your glb to see it in the real pipeline',
      report,
      result,
    }, null, 2));
  } catch (e) {
    console.error('submit failed:', e.message || e);
    res.statusCode = 400;
    res.end(JSON.stringify({ error: String(e.message || e) }));
  }
}
